// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingForDatabase.Data;

#nullable disable

namespace TrainingForDatabase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407091652_jhgfdsdsd")]
    partial class jhgfdsdsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Course 1"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Course 2"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Course 3"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Course 4"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Course 5"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseName = "Course 6"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseName = "Course 7"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseName = "Course 8"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseName = "Course 9"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseName = "Course 10"
                        },
                        new
                        {
                            CourseId = 11,
                            CourseName = "Course 11"
                        },
                        new
                        {
                            CourseId = 12,
                            CourseName = "Course 12"
                        },
                        new
                        {
                            CourseId = 13,
                            CourseName = "Course 13"
                        },
                        new
                        {
                            CourseId = 14,
                            CourseName = "Course 14"
                        },
                        new
                        {
                            CourseId = 15,
                            CourseName = "Course 15"
                        },
                        new
                        {
                            CourseId = 16,
                            CourseName = "Course 16"
                        },
                        new
                        {
                            CourseId = 17,
                            CourseName = "Course 17"
                        },
                        new
                        {
                            CourseId = 18,
                            CourseName = "Course 18"
                        },
                        new
                        {
                            CourseId = 19,
                            CourseName = "Course 19"
                        },
                        new
                        {
                            CourseId = 20,
                            CourseName = "Course 20"
                        },
                        new
                        {
                            CourseId = 21,
                            CourseName = "Course 21"
                        },
                        new
                        {
                            CourseId = 22,
                            CourseName = "Course 22"
                        },
                        new
                        {
                            CourseId = 23,
                            CourseName = "Course 23"
                        },
                        new
                        {
                            CourseId = 24,
                            CourseName = "Course 24"
                        },
                        new
                        {
                            CourseId = 25,
                            CourseName = "Course 25"
                        },
                        new
                        {
                            CourseId = 26,
                            CourseName = "Course 26"
                        },
                        new
                        {
                            CourseId = 27,
                            CourseName = "Course 27"
                        },
                        new
                        {
                            CourseId = 28,
                            CourseName = "Course 28"
                        },
                        new
                        {
                            CourseId = 29,
                            CourseName = "Course 29"
                        },
                        new
                        {
                            CourseId = 30,
                            CourseName = "Course 30"
                        },
                        new
                        {
                            CourseId = 31,
                            CourseName = "Course 31"
                        },
                        new
                        {
                            CourseId = 32,
                            CourseName = "Course 32"
                        },
                        new
                        {
                            CourseId = 33,
                            CourseName = "Course 33"
                        },
                        new
                        {
                            CourseId = 34,
                            CourseName = "Course 34"
                        },
                        new
                        {
                            CourseId = 35,
                            CourseName = "Course 35"
                        },
                        new
                        {
                            CourseId = 36,
                            CourseName = "Course 36"
                        },
                        new
                        {
                            CourseId = 37,
                            CourseName = "Course 37"
                        },
                        new
                        {
                            CourseId = 38,
                            CourseName = "Course 38"
                        },
                        new
                        {
                            CourseId = 39,
                            CourseName = "Course 39"
                        },
                        new
                        {
                            CourseId = 40,
                            CourseName = "Course 40"
                        });
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            name = "Operations"
                        },
                        new
                        {
                            Id = 7,
                            name = "Legal"
                        },
                        new
                        {
                            Id = 8,
                            name = "Customer Service"
                        },
                        new
                        {
                            Id = 9,
                            name = "Research and Development"
                        },
                        new
                        {
                            Id = 10,
                            name = "Supply Chain"
                        });
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            description = "Description 1",
                            name = "Item 1",
                            price = 570
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            description = "Description 2",
                            name = "Item 2",
                            price = 237
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            description = "Description 3",
                            name = "Item 3",
                            price = 315
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            description = "Description 4",
                            name = "Item 4",
                            price = 822
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            description = "Description 5",
                            name = "Item 5",
                            price = 695
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            description = "Description 6",
                            name = "Item 6",
                            price = 374
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            description = "Description 7",
                            name = "Item 7",
                            price = 2
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            description = "Description 8",
                            name = "Item 8",
                            price = 420
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            description = "Description 9",
                            name = "Item 9",
                            price = 137
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            description = "Description 10",
                            name = "Item 10",
                            price = 362
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 6,
                            description = "Description 11",
                            name = "Item 11",
                            price = 242
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 7,
                            description = "Description 12",
                            name = "Item 12",
                            price = 161
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 8,
                            description = "Description 13",
                            name = "Item 13",
                            price = 409
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 9,
                            description = "Description 14",
                            name = "Item 14",
                            price = 296
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 10,
                            description = "Description 15",
                            name = "Item 15",
                            price = 626
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            description = "Description 16",
                            name = "Item 16",
                            price = 794
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 2,
                            description = "Description 17",
                            name = "Item 17",
                            price = 283
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 3,
                            description = "Description 18",
                            name = "Item 18",
                            price = 777
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 4,
                            description = "Description 19",
                            name = "Item 19",
                            price = 951
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 5,
                            description = "Description 20",
                            name = "Item 20",
                            price = 212
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 6,
                            description = "Description 21",
                            name = "Item 21",
                            price = 198
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 7,
                            description = "Description 22",
                            name = "Item 22",
                            price = 300
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 8,
                            description = "Description 23",
                            name = "Item 23",
                            price = 256
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 9,
                            description = "Description 24",
                            name = "Item 24",
                            price = 391
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 10,
                            description = "Description 25",
                            name = "Item 25",
                            price = 300
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 1,
                            description = "Description 26",
                            name = "Item 26",
                            price = 827
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 2,
                            description = "Description 27",
                            name = "Item 27",
                            price = 772
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 3,
                            description = "Description 28",
                            name = "Item 28",
                            price = 789
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 4,
                            description = "Description 29",
                            name = "Item 29",
                            price = 510
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            description = "Description 30",
                            name = "Item 30",
                            price = 354
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 6,
                            description = "Description 31",
                            name = "Item 31",
                            price = 591
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 7,
                            description = "Description 32",
                            name = "Item 32",
                            price = 896
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 8,
                            description = "Description 33",
                            name = "Item 33",
                            price = 210
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 9,
                            description = "Description 34",
                            name = "Item 34",
                            price = 808
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 10,
                            description = "Description 35",
                            name = "Item 35",
                            price = 901
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 1,
                            description = "Description 36",
                            name = "Item 36",
                            price = 41
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 2,
                            description = "Description 37",
                            name = "Item 37",
                            price = 823
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 3,
                            description = "Description 38",
                            name = "Item 38",
                            price = 565
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 4,
                            description = "Description 39",
                            name = "Item 39",
                            price = 556
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 5,
                            description = "Description 40",
                            name = "Item 40",
                            price = 668
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 6,
                            description = "Description 41",
                            name = "Item 41",
                            price = 941
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 7,
                            description = "Description 42",
                            name = "Item 42",
                            price = 488
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 8,
                            description = "Description 43",
                            name = "Item 43",
                            price = 580
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 9,
                            description = "Description 44",
                            name = "Item 44",
                            price = 441
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 10,
                            description = "Description 45",
                            name = "Item 45",
                            price = 108
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 1,
                            description = "Description 46",
                            name = "Item 46",
                            price = 305
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 2,
                            description = "Description 47",
                            name = "Item 47",
                            price = 571
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 3,
                            description = "Description 48",
                            name = "Item 48",
                            price = 764
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 4,
                            description = "Description 49",
                            name = "Item 49",
                            price = 789
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 5,
                            description = "Description 50",
                            name = "Item 50",
                            price = 902
                        });
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Student 1"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Student 2"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Student 3"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Student 4"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Student 5"
                        },
                        new
                        {
                            StudentId = 6,
                            Name = "Student 6"
                        },
                        new
                        {
                            StudentId = 7,
                            Name = "Student 7"
                        },
                        new
                        {
                            StudentId = 8,
                            Name = "Student 8"
                        },
                        new
                        {
                            StudentId = 9,
                            Name = "Student 9"
                        },
                        new
                        {
                            StudentId = 10,
                            Name = "Student 10"
                        },
                        new
                        {
                            StudentId = 11,
                            Name = "Student 11"
                        },
                        new
                        {
                            StudentId = 12,
                            Name = "Student 12"
                        },
                        new
                        {
                            StudentId = 13,
                            Name = "Student 13"
                        },
                        new
                        {
                            StudentId = 14,
                            Name = "Student 14"
                        },
                        new
                        {
                            StudentId = 15,
                            Name = "Student 15"
                        },
                        new
                        {
                            StudentId = 16,
                            Name = "Student 16"
                        },
                        new
                        {
                            StudentId = 17,
                            Name = "Student 17"
                        },
                        new
                        {
                            StudentId = 18,
                            Name = "Student 18"
                        },
                        new
                        {
                            StudentId = 19,
                            Name = "Student 19"
                        },
                        new
                        {
                            StudentId = 20,
                            Name = "Student 20"
                        },
                        new
                        {
                            StudentId = 21,
                            Name = "Student 21"
                        },
                        new
                        {
                            StudentId = 22,
                            Name = "Student 22"
                        },
                        new
                        {
                            StudentId = 23,
                            Name = "Student 23"
                        },
                        new
                        {
                            StudentId = 24,
                            Name = "Student 24"
                        },
                        new
                        {
                            StudentId = 25,
                            Name = "Student 25"
                        },
                        new
                        {
                            StudentId = 26,
                            Name = "Student 26"
                        },
                        new
                        {
                            StudentId = 27,
                            Name = "Student 27"
                        },
                        new
                        {
                            StudentId = 28,
                            Name = "Student 28"
                        },
                        new
                        {
                            StudentId = 29,
                            Name = "Student 29"
                        },
                        new
                        {
                            StudentId = 30,
                            Name = "Student 30"
                        },
                        new
                        {
                            StudentId = 31,
                            Name = "Student 31"
                        },
                        new
                        {
                            StudentId = 32,
                            Name = "Student 32"
                        },
                        new
                        {
                            StudentId = 33,
                            Name = "Student 33"
                        },
                        new
                        {
                            StudentId = 34,
                            Name = "Student 34"
                        },
                        new
                        {
                            StudentId = 35,
                            Name = "Student 35"
                        },
                        new
                        {
                            StudentId = 36,
                            Name = "Student 36"
                        },
                        new
                        {
                            StudentId = 37,
                            Name = "Student 37"
                        },
                        new
                        {
                            StudentId = 38,
                            Name = "Student 38"
                        },
                        new
                        {
                            StudentId = 39,
                            Name = "Student 39"
                        },
                        new
                        {
                            StudentId = 40,
                            Name = "Student 40"
                        });
                });

            modelBuilder.Entity("TrainingForDatabase.Models.StudentCourses", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Item", b =>
                {
                    b.HasOne("TrainingForDatabase.Models.Department", "Department")
                        .WithMany("items")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Media", b =>
                {
                    b.HasOne("TrainingForDatabase.Models.Department", "Department")
                        .WithOne("Media")
                        .HasForeignKey("TrainingForDatabase.Models.Media", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.StudentCourses", b =>
                {
                    b.HasOne("TrainingForDatabase.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingForDatabase.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Course", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Department", b =>
                {
                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("items");
                });

            modelBuilder.Entity("TrainingForDatabase.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
